apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: gitops-prod-application-set
  namespace: argo-cd
spec:
  generators:
    - git:
        repoURL: 'git@github.com:jotto-tcc/gitops-dev.git'
        revision: try-application-set
        directories:
          - path: argocd/applications/telehealth/*
  template:
    metadata:
      name: '{{path.basename}}-applications'
    spec:
      project: telehealth
      source:
        repoURL: 'git@github.com:jotto-tcc/gitops-dev.git'
        targetRevision: main
        path: '{{path}}'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: argo-cd
      syncPolicy:
        automated:
          prune: true
          selfHeal: true