apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-fastapi
  namespace: client-projects
spec:
  podSelector:
    matchLabels:
      app: cardio-api
      deployment: ml-hrv-stress-level
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: cardio-api
              deployment: cardio-api