apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oauth2-proxy-cardio-api
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: client-projects
  project: client-projects
  sources:
    - repoURL: 'https://oauth2-proxy.github.io/manifests'
      targetRevision: 6.23.1
      chart: oauth2-proxy
      helm:
        values: |-
          config:
            existingSecret: oauth2-proxy-secret
            configFile: |-
              upstreams = [ "file:///dev/null" ]
              email_domains = [ "tcc-clinicalsolutions.de" , "swissanalytica.ch" ]
              provider = "keycloak-oidc"
              oidc_issuer_url = "https://keycloak.tcc-clinicalsolutions.de/realms/TCC"
              code_challenge_method = "S256"
              cookie_refresh = "4m30s"
              cookie_expire = "10h"
              allowed_roles = "cardio-api-docs-oauth-proxy:docs-user"

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
