apiVersion: v1
kind: Service
metadata:
  name: ml-hrv-stress-level-svc
  namespace: client-projects
spec:
  selector:
    app: cardio-api
    deployment: ml-hrv-stress-level
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000