apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hl7-receiver-dev
  name: deployment-hl7-receiver-dev
  namespace: telehealth-data-integration
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hl7-receiver-dev
  template:
    metadata:
      labels:
        app: hl7-receiver-dev
      name: hl7-receiver-dev
    spec:
      containers:
        - image: swr.eu-de.otc.t-systems.com/telehealth/telehealth-data-integration:v1.2.0-dev3
          envFrom:
            - secretRef:
                name: hl7-receiver-dev-secret
          command:
            - uvicorn
            - src.hl7_receiver.main:app
            - --host
            - 0.0.0.0
            - --port
            - '8000'
          name: hl7-receiver-dev
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
              name: api
      hostNetwork: false
      imagePullSecrets:
        - name: image-pull-secret
