apiVersion: v1
kind: Service
metadata:
  name: svc-hl7-receiver-dev
  namespace: telehealth-data-integration
spec:
  selector:
    app: hl7-receiver-dev
  ports:
    - protocol: TCP
      port: 8000
      name: hl7-recv
      targetPort: api
  type: ClusterIP
