---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: airflow-webserver-secret
  namespace: airflow
spec:
  encryptedData:
    webserver-secret-key: AgC689vA9a6O6p5wEBRJ7p6p2Zk0kxO9Wm/9ElyIILNYkxku91koHiTY9t8yP+W13wEprssKJKI6fTSyJLts/J2m/oyczLcoY80/doXX1JiA3aeyge8AqoHEAmRxp4FtOEoYGKDkEN0CqW1X6CV+sJyve/X0Hh60a5XYhQCadJ18pGi9cKMjjO0zokKE+aUYSPYMjbeEY8SmsOcgh2if5gpAAl0j8yD8xIFVNxlniO7W3RoSPC/LpjCNqUJ8J9jDesCH4bnO5ip7oxn2C2stTLDTUKuRrrG00ApMDGb7S0HXGsYaVh4L+f+g5T6ftqyUE+EbGQTV41+kE2Iz5Hvy5aV6nqzyfF/ICE++8LC+U+gaAN39ydNF/mJfdxtnLTsiNNN2OPfBR62hve13JfbmQ/smBGObIGfKti962yLSO4zIOODmXD0wtCfP2SuSYX6E/24IYCq/LF1qPQ/3v0PevSHu5HYaxbsi0un4LndAkxtC57JXjrJWC2/oPZateuqYRtFTOmvkknQXBsm/wZRkWB8C+pttv7NqdqkMGmQE2E0RiiIJWr4j8Ed5W3G9N/v1kADOGGouSfEUFPXYWB9NU9dhcX/Ci7TXvVTX5EmQgrk0gEM2mUv+pT6kHtaIU/k8KWJd3E3dZP2yLsGvfB1WeOUUPZ4ekl1qrIXxzPEPPnQbEYTZZyW+hN9/bQuMUhMi6S0fbuXbIHeUSHevRCTn49U9Y7+RWb0FyXDwcOAc3Cxq2A==
  template:
    metadata:
      creationTimestamp: null
      name: airflow-webserver-secret
      namespace: airflow
    type: Opaque
