---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: airflow-smtp-secret
  namespace: airflow
spec:
  encryptedData:
    password: AgAIxHn1meRwrR07ZFcHX6f0B+Dpb3egSFwPBvL8MPKIWxbTPilkEIeY/OrMilfiUKNXwU0+/PxfcmvZ5Kc1xQSNefO58H3qamgw8kwxE4tSAWR8EBclENg7i91mcNR0IQA2SXl7XSL5qZZz7bVAExvN8BdFfkdd8aDJsoRdBgNGT6JhIojN68QN8pN9GWq6bSoNb4PXMzsxtRb0P4cyG5WjO8sgMhJDzM3a0VZ4ve5KNBBAHrL6gu/U7BeGXsEzI+0vIT7FWxrdHptqM1UnEvEztrcLSW7IpsDUwqbMYAG3ByzuIgljOGApTWIP9Nvh1mRnnC0K4a5fiW4jRHSTIRZtIzu734NW5jHpbyLrjzzEGJ9ggSwfQ7eebsrUtl/13jx+88ee7z0nH1OESv7fRQtXaholM2MhxtiaMuyxq56mLwCwnUnThmQ5nNSZg3+terTWjzrJdE9AQapmZOr7Zr5QP3EHTb/fbz0iLmWFtv7M6gssRac9ekLot5213C89KOK2MrnynCvgoNyQmh/9K5juAg+4jHs7SNK2tcsZtOeEmSJEnlqVcOpM8ayXbP+7kBlnPLnyuCNVZ6ChN4byjcU5jqh3j+AaVIh5l+80MYaGpwVQyCFRi2i0sL5H4AGTDTBlI5Mc8MMIvQOIYvgcISM4ais0T7Om5fcTlk4igENCVgHrpZcg2Dmnsqiq+MOaeUyJ5fJITqVW2lmlCPh/8aZJDpphe+lUJUruUv5Fky8440XppkktMag=
    user: AgBWQHFKpdXSJlhf13qMzVHDBAUf9epY+DLUrbAGMer/1A/qz4PqzpWhtHgCmb2FIQR3gpYtadT0wekYIwQcjpKPA56u55ch5Mg6bQcd8TSHqOiYyeFnVx7Ta0v9x0HK5cBFTCMO9xXD7D9lqSv9d4OC6AQiMxWNLJP2A87wFNBt4jg6Sh20XHN1EZv8GBG2SPLORNCFGTBjmm9hRBk6JJfwksJYn+pGHts2wU6eNydnyDeFhrpfnYy+oMOqjBBRr4Wby2cXaaL2qp9lLa/RWvnRaQXyz+om8Jdx+unc4K3wbMV09qTTzM7WJa53rqlVbPr7/pkizsyaG8ahNpwPeP6mpxhramZYC9wCwyfp0t/8znSb/5RqXjYR1oCxILtivqc3qb5bqRXm+VolvasPERCCrelWq8qhDXgYV/xZ4h37LnlnjoIASAXHvK7y0f5KA9o6eC8hVCQIfExiVJXL+SDXBTs8yjnkzZQzQHIl4RIDbiFeVHy09PcMAvCYuY+PlLEgRFGLDelFXX3G9e8FcmpLAXTOWBsJByEHyCaZnDt9II5v+7K/a7/KJFtLpF9XONprXhzMthedEus/LA6pJ+kqAV34oyQgfbpm9bLOpqxVnvaAuJasqUPcxcsTQo+hyHtTv05utJfBJbZ3cFq3WgSLSFfqNmFn5D8AMPJiGW5PaAbw0q4l6akUOZTmKLM1+s29CgPiugrgidpcAfKcFd20qEipsRR/lS2m3GC9XX2H0Cqnuudr2F3t4EWaxuqEsA==
  template:
    metadata:
      creationTimestamp: null
      name: airflow-smtp-secret
      namespace: airflow
    type: Opaque
