apiVersion: v1
kind: ConfigMap
metadata:
  name: airflow-email-template
  namespace: airflow
data:
  content_template.j2: |
    Try {{try_number}} out of {{max_tries + 1}}<br>
    Exception:<br>{{exception_html}}<br>
    Log: <a href="{{ti.log_url}}">Link</a><br>
    Host: {{ti.hostname}}<br>
    Mark success: <a href="{{ti.mark_success_url}}">Link</a><br>
  subject_template.j2: |
    Airflow Job Failed: {{ ti.dag_id }}
