apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elmo-stg
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: telehealth
  source:
    repoURL: git@github.com:Telehealth-Competence-Center-GmbH/telehealth-gitops.git
    targetRevision: main
    path: telehealth-stg
    directory:
      recurse: true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: telehealth
  syncPolicy:
    automated:
      selfHeal: true
      prune: true