apiVersion: v1
kind: ConfigMap
metadata:
  name: docker-daemon-config
  namespace: arc-runners
# mtu: 1442
data:
  daemon.json: |
    {
      "mtu": 1400,
      "default-network-opts": {
        "bridge": {
         "com.docker.network.driver.mtu": "1400"
        }
      }
    }