apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arc-crds
  namespace: argo-cd
spec:
  destination:
    namespace: arc-systems
    server: https://kubernetes.default.svc
  project: infrastructure
  source:
    repoURL: https://github.com/actions/actions-runner-controller
    path: charts/gha-runner-scale-set-controller/crds
    directory:
      recurse: true
    targetRevision: gha-runner-scale-set-0.9.1
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - Replace=true
    automated:
      prune: true
      selfHeal: true

