apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arc
  namespace: argo-cd
spec:
  destination:
    namespace: arc-systems
    server: https://kubernetes.default.svc
  project: infrastructure
  source:
#    chart: oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set
    repoURL: oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set
    targetRevision: 0.8.2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

